---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - BUG
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.js"
  - "**.lock"
exclude_paths:
- "config/**/*"
- ".codeclimate.yml"
- "**.yml"
