language: ruby

sudo: false

cache: bundler

rvm:
 - 2.2

env:
  - DATABASE_URL=sqlite3:db/test.sqlite3

bundler_args: --without development --jobs=3 --retry=3

before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "cp config/site.yml.tmpl config/site.yml"

script: "bin/rake ci"

